# Generated by Django 4.1.13 on 2024-07-21 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.CharField(max_length=100)),
                ('level_classe', models.CharField(max_length=50)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort_name', models.CharField(max_length=50)),
                ('cohort_year', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalleFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salle_name', models.CharField(max_length=40)),
                ('capacity', models.CharField(max_length=10)),
                ('etage', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_seance', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('titre_module', models.CharField(max_length=100)),
                ('titre_cour', models.CharField(max_length=200)),
                ('effectif_present', models.IntegerField()),
                ('effectif_absent', models.IntegerField()),
                ('is_done', models.BooleanField(default=True)),
                ('observations', models.CharField(max_length=250)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='school.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='teachers.matiere')),
                ('salle_formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='school.salleformation')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='teachers.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialSalleFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count_item', models.IntegerField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_salle_formations', to='school.material')),
                ('salle_formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_salle_formations', to='school.salleformation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='school.cohort'),
        ),
    ]
