# Generated by Django 4.1.13 on 2024-07-21 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_event', models.DateField()),
                ('time_event', models.TimeField()),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendrier', to='school.seance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
